# print("hola mundo")
# nombre = input ()
# print("Mi nombre es:" + nombre) 

# Ejercicio Numero 1
# print("Ingrese su nombre:")
# nombre = input()
# print("Hola " + nombre + " ten un excelente dia <3")

# Ejercicio Numero 2
# print("Ingrese su nombre:")
# nombre = input()
# print("Ingresa tu edad:")
# edad = int(input())
# print("Edad: " + str(edad))
# print("Hola, ¡" + nombre + "! Tienes " + str(edad) + " años") 

# Ejercicio Numero 3
# print("Ingrese la temperatura en grados C: ")
# c = int(input ())
# f = (c * 9/5 + 32)
# print("La temperatura en F es: " + str(f))

# Ejercicio Numero 4
# print("Ingrese cantidad1: ")
# cantidad1 = int(input())
# print("Ingrese cantidad2: ")
# cantidad2 = int(input())

# suma = cantidad1 + cantidad2
# print("Suma =" + str(suma))

# resta = cantidad1 - cantidad2
# print("Resta =" + str(resta))

# multiplicacion = cantidad1 * cantidad2
# print("Multiplicacion =" + str(multiplicacion))

# division = cantidad1 / cantidad2
# print("Division =" + str(division))

# Ejercicio Numero 5
print("Ingrese la medida de la base: ")
base = int(input())
print("Ingrese la medida de la altura: ")
altura = int(input())
Area = ((base * altura)/2)
print("El area del triangulo es: " + str(Area))
